### ISSUE TITLE
Does not compile in 1.6.4 for Tiny841 on my core in v1.6.4 IDE

### ISSUE THREAD

**Issue by SpenceKonde** [orangkucing/WireS#1]
Several users are reporting that it doesn't compile. 

```
C:\Users\JUANCARLOS\Desktop\arduino-1.6.4\libraries\WireS-master/WireS.h:160:12: error: conflicting return type specified for 'virtual size_t i2c_tinyS::write(const uint8_t*, size_t)'
     size_t write(const uint8_t* data, size_t quantity);
            ^
In file included from C:\Users\JUANCARLOS\Documents\Arduino\hardware\arduino-tiny-841\avr\cores\tiny/Stream.h:24:0,
                 from C:\Users\JUANCARLOS\Documents\Arduino\hardware\arduino-tiny-841\avr\cores\tiny/HardwareSerial.h:28,
                 from C:\Users\JUANCARLOS\Documents\Arduino\hardware\arduino-tiny-841\avr\cores\tiny/WProgram.h:18,
                 from C:\Users\JUANCARLOS\Documents\Arduino\hardware\arduino-tiny-841\avr\cores\tiny/Arduino.h:4,
                 from C:\Users\JUANCARLOS\Desktop\arduino-1.6.4\libraries\HMC5983-master/HMC5983.h:13,
                 from BROADCASTER_FINAL_13MAYO.ino:5:
C:\Users\JUANCARLOS\Documents\Arduino\hardware\arduino-tiny-841\avr\cores\tiny/Print.h:75:18: error:   overriding 'virtual void Print::write(const uint8_t*, size_t)'
     virtual void write(const uint8_t *buffer, size_t size);
                  ^
In file included from BROADCASTER_FINAL_13MAYO.ino:6:0:
C:\Users\JUANCARLOS\Desktop\arduino-1.6.4\libraries\WireS-master/WireS.h:161:19: error: conflicting return type specified for 'virtual size_t i2c_tinyS::write(const char*)'
     inline size_t write(const char* str) { write((const uint8_t*)str, strlen(str)); }
                   ^
In file included from C:\Users\JUANCARLOS\Documents\Arduino\hardware\arduino-tiny-841\avr\cores\tiny/Stream.h:24:0,
                 from C:\Users\JUANCARLOS\Documents\Arduino\hardware\arduino-tiny-841\avr\cores\tiny/HardwareSerial.h:28,
                 from C:\Users\JUANCARLOS\Documents\Arduino\hardware\arduino-tiny-841\avr\cores\tiny/WProgram.h:18,
                 from C:\Users\JUANCARLOS\Documents\Arduino\hardware\arduino-tiny-841\avr\cores\tiny/Arduino.h:4,
                 from C:\Users\JUANCARLOS\Desktop\arduino-1.6.4\libraries\HMC5983-master/HMC5983.h:13,
                 from BROADCASTER_FINAL_13MAYO.ino:5:
C:\Users\JUANCARLOS\Documents\Arduino\hardware\arduino-tiny-841\avr\cores\tiny/Print.h:74:18: error:   overriding 'virtual void Print::write(const char*)'
     virtual void write(const char *str);

```

I'd love to help, but I've never written an I2C slave sketch and I'm not familiar with I2C on Arduino (i use I2C on Espruino, which exposes a very different API), and I just have no idea how to go about debugging this.

**Comment by orangkucing** [comment]
This is due to difference in prototypes. I've amended as [commit](https://github.com/orangkucing/WireS/commit/e5d0a80ebd1f0797fc750a10208918a6392a488a), so it should be compile now.

(It seems that `Print.h`, `Print.cpp`, `WString.h`, `WString.cpp` in `arduino-tiny-841/avr/cores/tiny` of current repo are a bit older and these does not support F() macro. Because I love this memory-conserving macro, I had copied these files from current ATmega's core and used with ATtiny841 and ATtiny1634.)

**Comment by SpenceKonde** [comment]
Sounds like a bug in my core, to me. 
I'd rather get the core fixed the right way, than having everyone (like you) have to work around it. 
I'll look into this and see if I can update those. (Any information more specific will be helpful to me in getting this sorted) 

On a different topic, did you do any testing with this library? If so, if you have any basic sketch that verifies that I2C functionality is working that I could use as part of my core verification test suite?

**Comment by orangkucing** [comment]
In order to get `F()` macro worked, I copied `Print.h`, `Print.cpp`, `WString.h`,  `WString.cpp` as well as `Printable.h` from mega's core.

Sure. For testing I'll upload some sketch today. :)

**Comment by SpenceKonde** [comment]
Thanks - I've fixed the print and string issues in the core by bringing in latest versions of those files, so you can back out the change there. I tested that it compiles with code from before that update. 

Are there any other files in my core that you've been replacing with newer versions? Let me know so I can do that in the core :-P

**Comment by orangkucing** [comment]
Thanks. I backed out the change there.
I've also added some sketches in example directory.

And while I wrote attiny841_i2c_analog I noticed there are typo in core_adc.h:

```
*** core_adc.h-old  Tue May 19 16:08:23 2015
--- core_adc.h  Tue May 19 16:10:26 2015
***************
*** 371,380 ****
    ADC_Input_ADC5            = B0101,
    ADC_Input_ADC6            = B0110,
    ADC_Input_ADC7            = B0111,
!   ADC_Input_ADC8            = B0111,
!   ADC_Input_ADC9            = B0111,
!   ADC_Input_ADC10           = B0111,
!   ADC_Input_ADC11           = B0111,

    ADC_Input_GND             = B1100,  // 0V (AGND)
    ADC_Input_1p1             = B1101,  // 1.1V (I Ref)
--- 371,380 ----
    ADC_Input_ADC5            = B0101,
    ADC_Input_ADC6            = B0110,
    ADC_Input_ADC7            = B0111,
!   ADC_Input_ADC8            = B1000,
!   ADC_Input_ADC9            = B1001,
!   ADC_Input_ADC10           = B1010,
!   ADC_Input_ADC11           = B1011,

    ADC_Input_GND             = B1100,  // 0V (AGND)
    ADC_Input_1p1             = B1101,  // 1.1V (I Ref)
```

But this is not related to the current discussion, I'm now going to close the issue.
